import type { Incident } from "@/types";
import { getStationInfo } from "@/config/constants";

function incidentToText(inc: Incident): string {
  const lines: string[] = [];
  lines.push("=".repeat(50));
  lines.push(`INCIDENT REPORT — ${inc.code}`);
  lines.push("=".repeat(50));
  lines.push("");
  lines.push(`Code:       ${inc.code}`);
  lines.push(`Date:       ${inc.date} (${inc.day})`);
  lines.push(`Time:       ${inc.time}`);
  lines.push(`Shift:      ${inc.shift}`);
  lines.push(`Station:    ${inc.station}`);
  lines.push(`Location:   ${inc.location}`);
  lines.push(`Type:       ${inc.incidentType}`);
  lines.push(`Severity:   ${inc.severity}`);
  lines.push(`Status:     ${inc.status}`);
  lines.push("");

  const d = inc.detection;
  if (d) {
    lines.push("--- Detection & Reporting ---");
    lines.push(`Discovered By: ${d.discoveredBy}`);
    lines.push(`Reported By:   ${d.reportedBy}`);
    lines.push(`OCC Notif:     ${d.occNotificationTime}`);
    lines.push(`OCC Response:  ${d.occResponseTime}`);
    lines.push(`Emergency:     ${d.emergencyCode}`);
    lines.push(`Permit:        ${d.permitNumber}`);
    lines.push("");
  }

  const p = inc.passenger;
  if (p) {
    lines.push("--- Passenger Data ---");
    lines.push(`Name:            ${p.name}`);
    lines.push(`Age:             ${p.age}`);
    lines.push(`Phone:           ${p.phone}`);
    lines.push(`Emergency:       ${p.emergencyContact}`);
    lines.push(`Status:          ${p.status}`);
    lines.push(`First Aid:       ${p.firstAidProvided}`);
    lines.push(`Ambulance Req:   ${p.ambulanceRequestTime || "—"}`);
    lines.push(`Ambulance Arr:   ${p.ambulanceArrivalTime || "—"}`);
    lines.push(`Hospital:        ${p.hospital || "—"}`);
    lines.push("");
  }

  const t = inc.trainOps;
  if (t) {
    lines.push("--- Train Operations ---");
    lines.push(`Train No:      ${t.trainNumber}`);
    lines.push(`Location:      ${t.currentLocation}`);
    lines.push(`Destination:   ${t.destination}`);
    lines.push(`Mode:          ${t.operationMode}`);
    lines.push(`Rescue Train:  ${t.rescueTrainNumber || "—"}`);
    lines.push("");
  }

  const e = inc.evacuation;
  if (e) {
    lines.push("--- Station Evacuation ---");
    lines.push(`OCC Order:    ${e.occOrderTime || "—"}`);
    lines.push(`Start:        ${e.evacuationStartTime || "—"}`);
    lines.push(`Complete:     ${e.evacuationCompleteTime || "—"}`);
    lines.push(`Reopen:       ${e.stationReopenTime || "—"}`);
    lines.push("");
  }

  const s = inc.staff;
  if (s) {
    lines.push("--- Staff ---");
    const addStaff = (label: string, m: { name: string; role: string } | undefined) => {
      if (m) lines.push(`${label}: ${m.name} (${m.role})`);
    };
    addStaff("Station Manager", s.sm);
    addStaff("Asst. Manager", s.asm);
    addStaff("Ambassador", s.sa);
    addStaff("Security", s.security);
    addStaff("Maintenance", s.maintenance);
    addStaff("Ambulance", s.ambulance);
    addStaff("Police", s.police);
    addStaff("Civil Defense", s.civilDefense);
    if (s.other.length > 0) {
      s.other.forEach((m, i) => lines.push(`Other #${i + 1}: ${m.name} (${m.role})`));
    }
    lines.push("");
  }

  const im = inc.impact;
  if (im) {
    lines.push("--- Impact Assessment ---");
    lines.push(`Duration:      ${im.incidentDuration} min`);
    lines.push(`Response:      ${im.responseDuration} min`);
    lines.push(`Injuries:      ${im.injuries}`);
    lines.push(`Fatalities:    ${im.fatalities}`);
    lines.push(`Train Delay:   ${im.trainDelay ? `${im.trainDelay} min` : "—"}`);
    lines.push(`Affected Pass: ${im.affectedPassengers}`);
    if (im.rootCause) lines.push(`Root Cause:    ${im.rootCause}`);
    if (im.correctiveActions) lines.push(`Actions:       ${im.correctiveActions}`);
    lines.push("");
  }

  lines.push("=".repeat(50));
  lines.push("Generated by Smart Metro Incident Management System");
  return lines.join("\n");
}

function reportsToText(incidents: Incident[]): string {
  const lines: string[] = [];
  lines.push("=".repeat(60));
  lines.push("INCIDENT REPORT SUMMARY");
  lines.push(`Generated: ${new Date().toLocaleString("en-GB")}`);
  lines.push("=".repeat(60));
  lines.push("");

  const resolved = incidents.filter(i => i.status === "RESOLVED");
  const totalInjuries = incidents.reduce((a, b) => a + (b.impact?.injuries || 0), 0);
  const totalFatalities = incidents.reduce((a, b) => a + (b.impact?.fatalities || 0), 0);
  const totalDelays = incidents.reduce((a, b) => a + (b.impact?.trainDelay || 0), 0);
  const avgDuration = incidents.length
    ? Math.round(incidents.reduce((a, b) => a + (b.impact?.incidentDuration || 0), 0) / incidents.length)
    : 0;

  lines.push("KPI SUMMARY");
  lines.push("-".repeat(40));
  lines.push(`Total Incidents: ${incidents.length}`);
  lines.push(`Closure Rate:    ${incidents.length ? Math.round((resolved.length / incidents.length) * 100) : 0}% (${resolved.length} closed)`);
  lines.push(`Total Injuries:  ${totalInjuries}`);
  lines.push(`Total Fatalities: ${totalFatalities}`);
  lines.push(`Total Delays:    ${totalDelays} min`);
  lines.push(`Avg Duration:    ${avgDuration} min`);
  lines.push("");

  lines.push("INCIDENT LIST");
  lines.push("-".repeat(60));
  incidents.forEach((inc, i) => {
    lines.push(`${i + 1}. ${inc.code} | ${inc.incidentType} | ${inc.station} | ${inc.severity} | ${inc.status} | ${inc.date}`);
  });
  lines.push("");
  lines.push("=".repeat(60));
  lines.push("Generated by Smart Metro Incident Management System");
  return lines.join("\n");
}

export function emailIncident(inc: Incident, to?: string) {
  const subject = encodeURIComponent(`Incident Report — ${inc.code}`);
  const body = encodeURIComponent(incidentToText(inc));
  window.open(`mailto:${to || ""}?subject=${subject}&body=${body}`, "_blank");
}

export function emailReport(incidents: Incident[], to?: string) {
  const subject = encodeURIComponent(`Incident Summary Report — ${new Date().toLocaleDateString("en-GB")}`);
  const body = encodeURIComponent(reportsToText(incidents));
  window.open(`mailto:${to || ""}?subject=${subject}&body=${body}`, "_blank");
}
