services:
  - type: web
    name: smart-metro-incident-management
    runtime: static
    buildCommand: npm run build
    staticPublishPath: dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
